export const PROFILE_PICTURE = 'https://jjmg-pictures.s3.amazonaws.com/square_profile_picture.png'
export const LINKEDIN_PROFILE = 'https://www.linkedin.com/in/juanjosedev/'
export const GITHUB_PROFILE = 'https://github.com/juanjosemayorga'
export const TWITTER_PROFILE = 'https://twitter.com/juanjosedev'
export const PLATZI_PROFILE = 'https://platzi.com/p/JuanJoseMayorga/'
export const FREECODECAMP_PROFILE = 'https://www.freecodecamp.org/juanjosemayorga'